### ISSUE TITLE
关于文件冲突的疑问

### ISSUE THREAD

**Issue by Yis92** [hust201010701/CheckResourceConflict#1]
请教两个问题：
1、为什么编译后的图片资源目录都会变成drawable-hdpi-v4 或者 mipmap-hdpi-v4 呢？
2、文件冲突处理的时候，只要app中有该文件插件就检测不出冲突了
盼回，谢谢～

**Comment by hust201010701** [comment]
@Yis92 https://www.wanandroid.com/wenda/show/9096 这个链接有类似问题的答案。
> “drawable-xxhdpi-v4”，后面的“v4”，就是最低兼容的版本，比如res下的“drawable-xxhdpi-v28”和“drawable-xxhdpi-v21”这两个文件夹下都有个"ic_test.png"，那么在运行的时候，9.0系统的手机显示的就是“v28”文件夹下的，而5.0的手机就显示"v21"的(如果这两张图片内容不一样的话就很容易看出来)。
> 
> 那么在做兼容的时候，比如要兼容到4.0，但项目中又用到了5.0以后才有的ripple效果，那就可以把这个用到了ripple的xml，放在"drawable-v21"文件夹里，同时保留原来drawable下的selector，这样，5.0以上系统，就会有ripple效果，而4.4及以下，则继续使用drawable下用selector实现的反馈效果。

下面说下我自己的理解，默认情况下编译后的资源文件所在的文件夹会自动带上「-v4」结尾，剩下的v13 以及 v21则是你依赖的aar包中指定的。

**Comment by Yis92** [comment]
明白，谢谢解惑，但是实际中我打印出来的 app module 下的 drawable-hdpi 并不带 v4
![11](https://user-images.githubusercontent.com/13741732/69772265-698aee00-11ca-11ea-9294-0da157fcb734.png)
![22](https://user-images.githubusercontent.com/13741732/69772268-6a238480-11ca-11ea-8fff-5d862533f8b8.png)
![34](https://user-images.githubusercontent.com/13741732/69772269-6a238480-11ca-11ea-91b4-c055f482c311.png)
![78](https://user-images.githubusercontent.com/13741732/69772270-6abc1b00-11ca-11ea-9df7-fd448de30451.png)

**Comment by hust201010701** [comment]
收到，这个问题的确设计的时候没有考虑到，等我查阅下编译期间资源处理的源码，再来修复下这个问题

**Comment by Yis92** [comment]
提个建议：
目前的文件对比策略是：文件目录名+文件名
是不是可以改为：如果文件名相同，再去判断两个文件是不是在同一个module下
文件名相同且不在同一个module下则认定为是冲突

**Comment by hust201010701** [comment]
这个策略不可行。举个例子：
module a 的 drawable-xxhdpi 下有个a.png， app 模块的 drawable-ldpi 下有个 a.png， 这种情况实际上不属于资源冲突，但是用你的策略会被误判成冲突。

我已经修复兼容了你说的情况，可以测试下看看。

**Comment by Yis92** [comment]
可以了 nice
