### ISSUE TITLE
不支持第三方SDK资源检测

### ISSUE THREAD

**Issue by kejunlu** [hust201010701/CheckResourceConflict#3]
本地module可以规范命名，但是接入的sdk查不出资源冲突

**Comment by hust201010701** [comment]
这个插件是可以检测sdk和依赖的module中的资源冲突的。你说的sdk中资源冲突能否具体说下资源所在目录和名称。

**Comment by kejunlu** [comment]
我测了2个module下同名的layout布局没检测出来

**Comment by kejunlu** [comment]
我自己测试错误
